import { useState } from "react";
import { getCookie, base64ToFile, isSurrogatePair, fileToBase64 } from "../auxFunctions";
import { IMAGE_EXTENSIONS, VIDEO_EXTENSIONS, AUDIO_EXTENSIONS } from "../aux_constants";
import type { Toast, Chat, Message, User } from "../types";
import { useParams } from "react-router";
import Header from "../Header";
import Menu from "../Menu";
import noProfilePhoto from "../assets/noprofilephoto.png"
import loading from "../assets/loading.gif"
import { Button } from "@radix-ui/themes";
import { Cross1Icon, PaperPlaneIcon, Pencil1Icon, UploadIcon } from "@radix-ui/react-icons";
import { VisuallyHidden } from "radix-ui";
import TextareaWithFormattingButtons from "../TextareaWithFormattingButtons";
import ToastsContainer from "../ToastsContainer";
import { marked } from "https://cdn.jsdelivr.net/npm/marked/lib/marked.esm.js";
import DOMPurify from "dompurify";
import "./ChatPage.css"
import EditChatDialog from "./EditChatDialog";

function ChatPage() {
    const files = document.querySelectorAll(".message-img, .message-video, .message-audio") as NodeListOf<HTMLImageElement | HTMLVideoElement | HTMLAudioElement>;
    for (let file of files) {
        const src = file.src;
        try {
            URL.revokeObjectURL(src);
        } catch {
            // Here we don't have to do anythiing:)
        }
    }

    const [myId, setMyId] = useState<number | null>(null);
    const [isLoading, setIsLoading] = useState({ chatInfo: true, myId: true });
    const [error, setError] = useState("");
    const [avatar, setAvatar] = useState<{ url: string, fileData: string | File } | null>(null);
    const [chatInfo, setChatInfo] = useState<Chat | null>(null);
    const [sentMessages, setSentMessages] = useState<Message[]>([]);
    const [autoGeneratedMessages, setAutoGeneratedMessages] = useState<Message[]>([]);
    const [currentMessage, setCurrentMessage] = useState({ text: "", media: [] as { url: string, fileData: File }[] });
    const [isEditDialogOpen, setIsEditDialogOpen] = useState(false);
    const [toasts, setToasts] = useState<Toast[]>([]);

    const { id: chatId } = useParams();

    function getFileSrc(img: { url: string, fileData: string | File }) {
        if (typeof img.fileData === "string") {
            if (img.url === img.fileData) return img.url;
            return URL.createObjectURL(base64ToFile(img.fileData));
        }

        return URL.createObjectURL(img.fileData);
    }

    if (isLoading.myId) {
        const userResponse = fetch("/api/info-about-me", {
            headers: {
                "Authorization": `Bearer ${getCookie("jwt-token")}`
            }
        });
        userResponse.then(res => {
            if (res.ok) {
                return res.json()
            } else {
                setToasts(toasts.concat({ headerContent: "Ошибка", bodyContent: "Не удалось получить информацию о текущем пользователе" }))
            }
        }).then(json => {
            if (json) {
                setMyId(json.id);
            }
        }).finally(() => setIsLoading({ ...isLoading, myId: false }));
    }

    if (myId && isLoading.chatInfo) {
        const response = fetch(`/api/chats/${chatId}`, {
            headers: {
                "Authorization": `Bearer ${getCookie("jwt-token")}`
            }
        });
        response.then(res => {
            if (res.ok) {
                return res.json();
            } else {
                if (res.status === 403) {
                    setError("Вы не состоите в этом чате");
                } else if (res.status === 404) {
                    setError("Чата с таким id не существует");
                } else {
                    setError("Неизвестная ошибка");
                }
            }
        }).then((json: Chat) => {
            if (json) {
                setChatInfo(json);
                updateChatMessages(json.id);

                if (!json.avatar && json.participants.length === 2) {
                    const secondUser = json.participants.filter(item => item.id != myId)[0];
                    updateAvatar(secondUser.id);
                } else if (json.avatar) {
                    setAvatar(json.avatar)
                }
            }
        }).finally(() => setIsLoading({ ...isLoading, chatInfo: false }));
    }

    function updateAvatar(userId: number) {
        const response = fetch(`/api/users/${userId}`);
        response.then(res => {
            if (res.ok) return res.json();
        }).then((data: User) => {
            if (data) {
                const avatar = data.avatar;
                if (avatar) {
                    try {
                        const fileData = base64ToFile(avatar);
                        setAvatar({ url: "Аватар", fileData: fileData });
                    } catch {
                        setAvatar({ url: avatar, fileData: avatar });
                    }
                }
            }
        })
    }

    function updateChatMessages(chatId: number) {
        const response = fetch(`/api/chat-messages/${chatId}`);
        response.then(res => {
            if (res.ok) return res.json();
            setToasts(toasts.concat({ headerContent: "Ошибка", bodyContent: "Не удалось получить сообщения чата" }));
        }).then((data: Message[]) => {
            if (data) {
                let autoGeneratedToAdd = [] as Message[];
                let sentToAdd = [] as Message[];

                for (let message of data) {
                    if (message.imitate_generation) {
                        autoGeneratedToAdd.push(message);
                    } else {
                        sentToAdd.push(message);
                    }
                }

                setAutoGeneratedMessages(autoGeneratedToAdd.sort((first, second) => first.id >= second.id ? 1 : -1));
                setSentMessages(sentToAdd.sort((first, second) => first.id >= second.id ? 1 : -1));
                window.scrollTo({ top: document.body.scrollHeight, behavior: "auto" });
            }
        })
    }

    async function handleSubmit(event: React.SubmitEvent<HTMLFormElement>) {
        event.preventDefault();
        if (!chatInfo) return;
        let filesToSend = [];

        for (let file of currentMessage.media) {
            const fileAsBase64 = await fileToBase64(file.fileData);
            filesToSend.push({ url: file.url, fileData: fileAsBase64 });
        }

        if (!currentMessage.text && !currentMessage.media.length) {
            setToasts(toasts.concat({ headerContent: "Ошибка", bodyContent: "Сообщение должно содержать текст и/или прикреплённые файлы" }));
            return;
        }

        const response = fetch("/api/messages", {
            method: "POST",
            body: JSON.stringify({
                ...currentMessage,
                media: filesToSend,
                chatID: chatInfo.id,
                senderID: myId
            }),
            headers: {
                'Content-Type': 'application/json'
            },
        });
        response.then(res => {
            if (res.ok) {
                updateChatMessages(chatInfo.id);
                setCurrentMessage({ text: "", media: [] });
            } else {
                setToasts(toasts.concat({ headerContent: "Ошибка", bodyContent: "При отправке сообщения произошла ошибка" }))
            }
        })
    }

    if (autoGeneratedMessages.length && !currentMessage.text) {
        const firstMessage = autoGeneratedMessages[0];

        if (firstMessage.senderID == myId) {
            if (firstMessage.text.length == 1) setCurrentMessage({
                ...currentMessage,
                text: firstMessage.text
            })

            let i = 0;
            let intervalId: number;

            intervalId = setInterval(() => {
                if (i < firstMessage.text.length - 1 && isSurrogatePair(firstMessage.text[i], firstMessage.text[i + 1])) {
                    setCurrentMessage({
                        ...currentMessage,
                        text: firstMessage.text.slice(0, i + 2)
                    });

                    i += 2;
                } else {
                    setCurrentMessage({
                        ...currentMessage,
                        text: firstMessage.text.slice(0, i + 1)
                    });

                    i++;
                }

                if (i == firstMessage.text.length) {
                    clearInterval(intervalId);
                    setTimeout(() => {
                        setAutoGeneratedMessages(autoGeneratedMessages.filter(item => item !== firstMessage));
                        setSentMessages(sentMessages.concat(firstMessage));
                        setCurrentMessage({ text: "", media: [] });
                        window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" });
                    }, 100);
                }
            }, 250);
        } else {
            setTimeout(() => {
                setAutoGeneratedMessages(autoGeneratedMessages.filter(item => item !== firstMessage));
                setSentMessages(sentMessages.concat(firstMessage));
                window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" });
            }, 100 * firstMessage.text.length + 500 * (firstMessage.media?.length || 0));
        }
    }

    return (
        <>
            <title>{isLoading.chatInfo && !chatInfo ? "Загрузка..." : chatInfo?.name || `Чат с пользователем ${chatInfo?.participants.filter(item => item.id !== myId)[0].username}` || "Название неизвестно"}</title>
            <div className="page-wrapper chat-page-wrapper">
                <Header />
                <Menu />
                <main className={`main chat-main ${currentMessage.media.length ? "chat-main-small" : ""}`}>
                    {(isLoading.chatInfo && !chatInfo) ? <p>Загрузка...</p> : error ? `Ошибка: ${error}` : ""}
                    {chatInfo ? <>
                        <div className="chat-header">
                            <img src={avatar ? getFileSrc(avatar) : isLoading.chatInfo ? loading : noProfilePhoto} alt="" className="chat-avatar" />
                            <h2 className="heading chat-name">{chatInfo.is_name_auto_generated ? chatInfo.participants.filter(item => item.id != myId)[0].username : chatInfo.name}</h2>
                            {chatInfo?.admins.map(a => a.id).includes(myId || -1) ? <Button onClick={() => setIsEditDialogOpen(true)}><Pencil1Icon /></Button> : ""}
                        </div>
                        <div className="chat-messages">
                            {sentMessages.length ? sentMessages.map(
                                message =>
                                    <div key={message.id} className={`message ${message.senderID === myId ? "my-message" : "others-message"}`}>
                                        <span className="message-text" dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(marked(message.text)) }} />
                                        {message.media ?
                                            <div className="message-media">
                                                <div className="message-images">
                                                    {
                                                        message.media.filter(item => IMAGE_EXTENSIONS.includes(item.url.slice(item.url.lastIndexOf(".")))).map(
                                                            (img, index) => <img src={getFileSrc(img)} alt={`Изображение ${index}`} key={index} className="message-image" />
                                                        )
                                                    }
                                                </div>
                                                <div className="message-videos">
                                                    {
                                                        message.media.filter(item => VIDEO_EXTENSIONS.includes(item.url.slice(item.url.lastIndexOf(".")))).map(
                                                            (vid, index) => <video src={getFileSrc(vid)} key={index} className="message-video" />
                                                        )
                                                    }
                                                </div>
                                                <div className="message-audios">
                                                    {
                                                        message.media.filter(item => AUDIO_EXTENSIONS.includes(item.url.slice(item.url.lastIndexOf(".")))).map(
                                                            (audio, index) => <audio src={getFileSrc(audio)} key={index} className="message-audio" />
                                                        )
                                                    }
                                                </div>
                                            </div>
                                            : ""
                                        }
                                    </div>
                            ) : <p>Сообщений пока нет</p>}
                        </div>
                        <form className="message-send-wrapper" onSubmit={handleSubmit}>
                            <input type="file" hidden id="file-add-input" multiple accept="image/*,audio/*,video/*"
                                onChange={event => {
                                    const files = event.target.files;
                                    if (files) {
                                        let appropriateFiles = [] as { url: string, fileData: File }[];
                                        for (let file of files) {
                                            const extension = file.name.slice(file.name.lastIndexOf("."));
                                            if (!IMAGE_EXTENSIONS.includes(extension) && !VIDEO_EXTENSIONS.includes(extension) && !AUDIO_EXTENSIONS.includes(extension)) {
                                                setToasts(toasts.concat({ headerContent: "Уведомление", bodyContent: `Расширение файла ${file.name} не поддерживается, поэтому он не был добавлен` }));
                                                continue;
                                            }

                                            appropriateFiles.push({ url: file.name, fileData: file })
                                        }

                                        setCurrentMessage(
                                            {
                                                ...currentMessage,
                                                media: currentMessage.media.concat(appropriateFiles)
                                            }
                                        );
                                    }
                                }}
                            />
                            <Button type="button" id="fake-file-add" onClick={() => document.getElementById("file-add-input")?.click()}><UploadIcon /><VisuallyHidden.Root>Прикрепить файлы</VisuallyHidden.Root></Button>
                            <TextareaWithFormattingButtons id="message-text" text={currentMessage.text} setText={(newText: string) => setCurrentMessage({
                                ...currentMessage,
                                text: newText
                            })} readOnly={autoGeneratedMessages.length !== 0} />
                            <Button disabled={autoGeneratedMessages.length !== 0} className="send-message-button"><PaperPlaneIcon /><VisuallyHidden.Root>Отправить сообщение</VisuallyHidden.Root></Button>
                            <div className="attached-files">
                                {currentMessage.media.map((item, index) => <div className="attached-file-chip" key={index}>{item.url} <button type="button" className="transparent-button" onClick={() => setCurrentMessage({
                                    ...currentMessage,
                                    media: currentMessage.media.filter(file => file != item)
                                })}><Cross1Icon /><VisuallyHidden.Root>Удалить файл</VisuallyHidden.Root></button></div>)}
                            </div>
                        </form>
                        {myId && chatInfo.admins.map(a => a.id).includes(myId) ? <EditChatDialog isOpen={isEditDialogOpen} setIsOpen={setIsEditDialogOpen} chatInfo={chatInfo} myId={myId} onUpdate={() => setIsLoading({ ...isLoading, chatInfo: true })} /> : ""}
                    </> : ""
                    }
                    <ToastsContainer toasts={toasts} />
                </main>
            </div>
        </>
    )
}

export default ChatPage;