import { useParams } from "react-router";
import { useEffect, useState } from "react";
import { Button, Form } from "react-bootstrap";
import Header from "../Header";
import SearchByNameOrId from "../SearchByNameOrId";
import { type Toast as ToastType, type Message, type HasNameAndId, type CreateProps, type LoadingStatus, type HasUsernameAndId } from "../types";
import FileAttachment from "../FileAttachment";
import TextareaWithFormattingButtons from "../TextareaWithFormattingButtons";
import CustomToastsContainer from "../CustomToastsContainer";

async function getMessageDataByID(id: number) {
    const response = await fetch(`/api/messages/${id}`);
    if (!response.ok) {
        const errorDetails = await response.json();
        throw new Error(errorDetails.detail || "Ошибка загрузки сообщения");
    }
    return response.json();
}

function MessagesCreate({ label }: CreateProps) {
    document.title = `${label} сообщения`
    const { id: messageId } = useParams();

    const [chat, setChat] = useState<HasNameAndId & { participants?: HasUsernameAndId[] }>({ name: "", id: -1, participants: [] });
    const [chatValue, setChatValue] = useState("");
    const [chatSearchResults, setChatSearchResults] = useState<HasNameAndId[]>([]);
    const [areChatSearchResultsLoading, setAreChatSearchResultsLoading] = useState(false);
    const [sender, setSender] = useState({ name: "", id: -1 });
    const [senderValue, setSenderValue] = useState("");
    const [senderSearchResults, setSenderSearchResults] = useState<HasNameAndId[]>([]);
    const [areSenderSearchResultsLoading, setAreSenderSearchResultsLoading] = useState(false);
    const [text, setText] = useState("");
    const [isAutogenerated, setIsAutogenerated] = useState(false);
    const [toasts, setToasts] = useState<ToastType[]>([]);
    const [error, setError] = useState("");
    const [isDataLoading, setIsDataLoading] = useState(Boolean(messageId));
    const [attachedFiles, setAttachedFiles] = useState<{ url: string, fileData: string | File }[]>([]);
    const [isAddingFile, setIsAddingFile] = useState(false);
    const [newFileUrl, setNewFileUrl] = useState("");
    const [loadingStatus, setLoadingStatus] = useState<LoadingStatus>({ ok: 0, message: "Подождите, медиа загружается..." });

    function createToast(headerMessage: string, bodyMessage: string) {
        const newToast = { headerContent: headerMessage, bodyContent: bodyMessage };
        return newToast;
    }

    async function getChatData(chatId: number): Promise<{ name: string, participants: HasUsernameAndId[] } | null> {
        const response = await fetch(`/api/chats/${chatId}`);
        if (response.ok) {
            const json = await response.json();
            return { name: json.name, participants: json.participants };
        }

        return null;
    }

    async function getSenderName(senderId: number) {
        const response = await fetch(`/api/users/${senderId}`);
        if (response.ok) {
            const json = await response.json();
            return json.username;
        }

        return null;
    }

    useEffect(() => {
        if (!messageId) {
            setIsDataLoading(false);
            return;
        }

        setIsDataLoading(true);
        getMessageDataByID(Number(messageId))
            .then((res: Message) => {
                if (res) {
                    setText(res.text);
                    setIsAutogenerated(!!res.imitate_generation)
                    if (res.media) setAttachedFiles(res.media.map(item => { return { url: item, fileData: item } }));

                    const senderName = getSenderName(Number(res.senderID));
                    senderName.then(senderRes => {
                        const newSender = { id: Number(res.senderID), name: senderRes };

                        setSender(newSender);
                        setSenderValue(`${senderRes}, ID: ${res.senderID}`)
                        setSenderSearchResults([newSender]);
                    });

                    const chatName = getChatData(Number(res.chatID));
                    chatName.then(chatRes => {
                        if (chatRes) {
                            const newChat = { id: Number(res.chatID), ...chatRes };

                            setChat(newChat);
                            setChatValue(`${chatRes.name ? chatRes.name : "Чат с автогенерируемым названием"}, ID: ${res.chatID}`);
                            setChatSearchResults([newChat])
                        }
                    })
                }
            })
            .catch((err: Error) => setError(err.message))
            .finally(() => setIsDataLoading(false));
    }, [messageId]);

    useEffect(() => {
        const userIds = chat.participants?.map(user => user.id) || [];
        const filteredResults = senderSearchResults.filter(item => userIds.includes(item.id));

        if (senderSearchResults.length > filteredResults.length) {
            setSenderSearchResults(filteredResults);
        }
    }, [senderSearchResults])

    function handleSubmit(event: React.SubmitEvent<HTMLFormElement>) {
        event.preventDefault();
        let toastsToAdd = [];

        if (text.trim() && senderSearchResults.includes(sender) && chatSearchResults.includes(chat)) {
            const response = postMessageData();
            response.then(res => {
                if (res.ok) {
                    setToasts(toasts.concat({ headerContent: "Уведомление", bodyContent: "Данные успешно сохранены" }));
                    setTimeout(() => window.location.href = "/", 500);
                } else {
                    setToasts(toasts.concat({ headerContent: "Ошибка", bodyContent: "Не удалось сохранить данные на сервере" }));
                }
            });
        } else {
            if (!text.trim()) {
                toastsToAdd.push(createToast("Ошибка", "Введите текст сообщения"));
            }
            if (!senderSearchResults.includes(sender)) {
                toastsToAdd.push(createToast("Ошибка", "Выберите отправителя"));
            }
            if (!chatSearchResults.includes(chat)) {
                toastsToAdd.push(createToast("Ошибка", "Выберите чат"));
            }
        }

        setToasts(toasts.concat(toastsToAdd));
    }

    function postMessageData() {
        const reqBody = messageId ? {
            id: messageId,
            chatID: chat.id,
            text: text,
            senderID: sender.id,
            imitate_generation: isAutogenerated
        } : {
            chatID: chat.id,
            text: text,
            senderID: sender.id,
            imitate_generation: isAutogenerated
        }
        const response = fetch("/api/messages", {
            method: "POST",
            body: JSON.stringify(reqBody),
            headers: {
                'Content-Type': 'application/json'
            },
        });

        return response;
    }

    return (
        <>
            <Header />
            <main className="main">
                <h2 className="heading heading-level-2">{label} сообщения</h2>
                {isDataLoading ? <p>Загрузка...</p> : error ? <p>Ошибка: {error}</p> :
                    <form onSubmit={handleSubmit} className="create-form">
                        <Form.Label htmlFor="chat">
                            Название или ID чата
                        </Form.Label>
                        <SearchByNameOrId entityType="chat" id="chat" inputValue={chatValue} changeInputValue={setChatValue}
                            searchResults={{
                                resultsArray: chatSearchResults,
                                areLoading: areChatSearchResultsLoading
                            }}
                            changeSearchResultsStatus={setAreChatSearchResultsLoading}
                            changeSearchResultsArray={setChatSearchResults}
                            changeEntity={setChat}
                        />
                        <Form.Label htmlFor="text">
                            Текст сообщения
                        </Form.Label>
                        <TextareaWithFormattingButtons text={text} setText={setText} id="text"/>
                        <Form.Check checked={isAutogenerated} label="Имитировать написание" onChange={event => setIsAutogenerated(event.target.checked)} id="imitate-generation"/>
                        <Form.Label htmlFor="sender">
                            Отправитель
                        </Form.Label>
                        <SearchByNameOrId id="sender" inputValue={senderValue} changeInputValue={setSenderValue}
                            searchResults={{
                                resultsArray: senderSearchResults,
                                areLoading: areSenderSearchResultsLoading
                            }}
                            changeSearchResultsStatus={setAreSenderSearchResultsLoading}
                            changeSearchResultsArray={setSenderSearchResults}
                            changeEntity={setSender} />
                        <FileAttachment newFileSrc={newFileUrl} setNewFileSrc={setNewFileUrl} loadingStatus={loadingStatus} setLoadingStatus={setLoadingStatus} isAddingFile={isAddingFile} setIsAddingFile={setIsAddingFile} attachedFiles={attachedFiles} setAttachedFiles={setAttachedFiles} />
                        <Button type="submit" style={{ marginTop: "16px" }}>Сохранить</Button>
                    </form>
                }

                <CustomToastsContainer toasts={toasts} setToasts={setToasts} />
            </main>
        </>
    )
}

export default MessagesCreate;