import { useState, useEffect, useRef } from "react";
import { useParams } from "react-router";
import React from "react";
import Header from "../Header";
import AddByNameOrId from "../AddByNameOrId";
import Form from "react-bootstrap/Form";
import InputGroup from 'react-bootstrap/InputGroup';
import Button from "react-bootstrap/Button";
import CustomToastsContainer from "../CustomToastsContainer";
import { Col, Overlay, Tab, Tabs } from "react-bootstrap";
import { QuestionCircleFill } from "react-bootstrap-icons";
import "./ChatsCreate.css"
import { type Chat, type CreateProps, type HasNameAndId, type Toast as ToastType } from "../types";
import { IMAGE_EXTENSIONS } from "../auxConstants";
import AvatarPreview from "../AvatarPreview";
import { fileToBase64, getImageAsFile } from "../auxFunctions";


async function getChatDataByID(id: number) {
    const response = await fetch(`/api/chats/${id}`);
    if (response.ok) {
        const json = await response.json();
        return json;
    }
    const errorDetails = await response.json();
    throw new Error(errorDetails.detail)
}

function ChatsCreate(props: CreateProps) {
    document.title = `${props.label} чата`
    const { id: chatId } = useParams();
    const target = useRef(null);

    const [chatName, setChatName] = useState("");
    const [participants, setParticipants] = useState<HasNameAndId[]>([]);
    const [admins, setAdmins] = useState<HasNameAndId[]>([]);
    const [avatar, setAvatar] = useState("");
    const [avatarIsLocal, setAvatarIsLocal] = useState(false);
    const [fileObj, setFileObj] = useState<File | null>(null);
    const [toasts, setToasts] = useState<ToastType[]>([]);
    const [isDataLoading, setIsDataLoading] = useState(isFinite(Number(chatId))); // Если мы редактируем чат (есть ID), то нам нужно подгрузить данные
    const [isNameAutoGenerated, setIsNameAutoGenerated] = useState(false);
    const [error, setError] = useState("");
    const [tooltipIsShown, setTooltipIsShown] = useState(false);

    function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
        if (event.target.value.length <= 30) {
            setChatName(event.target.value);
        }
    }

    function handleSubmit(event: React.SubmitEvent<HTMLFormElement>) {
        event.preventDefault();
        let toastsToAdd = [];
        if ((chatName.trim() || isNameAutoGenerated) && participants.length) {
            const response = postChatData();
            response.then(res => {
                if (res.ok) {
                    toastsToAdd.push(createToast("Уведомление", "Данные успешно сохранены"));
                    setTimeout(() => window.location.href = "/", 500);
                } else {
                    toastsToAdd.push(createToast("Ошибка", "Не удалось сохранить данные на сервере"));
                }

                setToasts(toasts.concat(toastsToAdd));
            });
        } else {
            if (!chatName.trim() && !isNameAutoGenerated) {
                toastsToAdd.push(createToast("Ошибка", "Введите название чата"));
            }
            if (!participants.length) {
                toastsToAdd.push(createToast("Ошибка", "Добавьте хотя бы одного участника в чат"));
            }

            setToasts(toasts.concat(toastsToAdd));
        }
    }

    async function postChatData() {
        console.log(fileObj);
        const base64Str = fileObj ? await fileToBase64(fileObj) : "";

        const reqBody = chatId ? {
            id: chatId,
            name: chatName,
            participants: participants.map(item => {
                return {
                    id: item.id,
                    username: item.name
                }
            }),
            is_name_auto_generated: isNameAutoGenerated,
            avatar: fileObj ? { url: fileObj.name, fileData: base64Str } : { url: avatar, fileData: avatar },
            admins: admins
        } : {
            name: chatName,
            participants: participants.map(item => {
                return {
                    id: item.id,
                    username: item.name
                }
            }),
            is_name_auto_generated: isNameAutoGenerated,
            avatar: fileObj ? { url: fileObj.name, fileData: base64Str } : { url: avatar, fileData: avatar },
            admins: admins
        }
        const response = fetch("/api/chats", {
            method: "POST",
            body: JSON.stringify(reqBody),
            headers: {
                'Content-Type': 'application/json'
            },
        });

        return response;
    }

    function createToast(headerMessage: string, bodyMessage: string) {
        const newToast = { headerContent: headerMessage, bodyContent: bodyMessage };
        return newToast;
    }

    useEffect(() => {
        if (chatId) {
            const data = getChatDataByID(Number(chatId));
            data.then((res: Chat & { is_name_auto_generated: boolean }, err?: Error) => {
                if (!err) {
                    setParticipants(res.participants.map(item => {
                        return {
                            id: item.id,
                            name: item.username
                        }
                    }));
                    setChatName(res.name);
                    setIsNameAutoGenerated(res.is_name_auto_generated)
                    const avatarAsFile = getImageAsFile(res.avatar?.fileData || "");
                    if (avatarAsFile) {
                        setFileObj(avatarAsFile);
                    } else if (res.avatar) {
                        setAvatar(res.avatar.url)
                    }
                    setAvatarIsLocal(Boolean(avatarAsFile));
                    setAdmins(res.admins.map(item => {
                        return {
                            ...item,
                            name: item.username
                        }
                    }));
                }
            })
                .catch((err: Error) => setError(err.message))
                .finally(
                    () => setIsDataLoading(false)
                );
        } else if (isDataLoading) {
            setTimeout(() => setIsDataLoading(false), 0);
        }
    }, []);

    useEffect(() => setIsDataLoading(true), [chatId]);
    useEffect(() => {
        if (participants.length !== 2) {
            setIsNameAutoGenerated(false);
        }
    }, [participants])

    return (
        <>
            <Header />
            <main className="main">
                <h2 className="heading heading-level-2">{props.label} чата</h2>{isDataLoading ? <p>Загрузка...</p> : error ? <p>Ошибка: {error}</p> :
                    <>
                        <form onSubmit={handleSubmit}>
                            <Form.Label htmlFor="chat-name">Название чата</Form.Label>
                            <Col sm="6" md="4" lg="3">
                                <InputGroup >
                                    <Form.Control width="90" type="text" autoComplete="off" id="chat-name" value={isNameAutoGenerated ? "<Название генерируется автоматически>" : chatName} onChange={handleChange} readOnly={isNameAutoGenerated} />
                                    <InputGroup.Text hidden={isNameAutoGenerated}>{30 - chatName.length}</InputGroup.Text>
                                </InputGroup>
                            </Col>
                            <Form.Text hidden={isNameAutoGenerated}>Длина названия - не более 30 символов</Form.Text>
                            <div className="auto-generation-wrapper">
                                <Form.Check label="Автогенерация названия" checked={isNameAutoGenerated} onChange={e =>
                                    setIsNameAutoGenerated(e.target.checked)} id="is-name-auto-generated" disabled={participants.length !== 2} />
                                <Button variant="link" ref={target} onClick={() => setTooltipIsShown(!tooltipIsShown)}><QuestionCircleFill /></Button>
                                <Overlay target={target.current} show={tooltipIsShown} placement="bottom">
                                    <div className="tooltip-inner">
                                        Поддерживается только для чатов с двумя участниками
                                    </div>
                                </Overlay>
                            </div>
                            <hr />
                            <h3 className="heading heading-level-3">Участники чата</h3>
                            <AddByNameOrId entities={participants} ChangeEntities={setParticipants} toasts={toasts} changeToasts={setToasts} />
                            <h3 className="heading heading-level-3">Администраторы</h3>
                            <AddByNameOrId entities={admins} ChangeEntities={setAdmins} toasts={toasts} changeToasts={setToasts} condition={item => participants.map(p => p.id).includes(item.id)} />
                            <div className="avatar-add-wrapper">
                                <h3 className="heading heading-level-3">Аватар чата</h3>
                                <Tabs onSelect={key => {
                                    if (key !== "local" && avatarIsLocal || key === "local" && !avatarIsLocal) {
                                        setAvatar("");
                                        setFileObj(null);
                                    }
                                    setAvatarIsLocal(key === "local");
                                }} activeKey={avatarIsLocal ? "local" : "internet-link"}>
                                    <Tab title="Из Интернета" eventKey="internet-link">
                                        <div className="avatar-add-wrapper">
                                            <Form.Label htmlFor="group-avatar">Ссылка на аватар</Form.Label>
                                            <Form.Control id="group-avatar" value={avatar} onChange={(event) => setAvatar(event.target.value)} />
                                        </div>
                                    </Tab>
                                    <Tab title="Из локального хранилища" eventKey="local">
                                        <div className="avatar-add-wrapper">
                                            <input type="file" id="file-picker" hidden accept="image/*" onChange={event => {
                                                const file = event.target.files?.item(0);
                                                if (file) {
                                                    if (IMAGE_EXTENSIONS.includes(file.name.slice(file.name.lastIndexOf(".")))) {
                                                        setAvatar(URL.createObjectURL(file));
                                                        setFileObj(file);
                                                    }
                                                }
                                            }} />
                                            <Button onClick={() => {
                                                document.getElementById("file-picker")?.click();
                                            }}>Выбрать файл</Button>
                                        </div>
                                    </Tab>
                                </Tabs>
                                <div className="preview" style={{ marginTop: "10px" }}>
                                    <AvatarPreview url={avatar} alt="Превью аватара группы" emptyMessage={`${avatarIsLocal ? "Выберите файл" : "Введите ссылку на аватар"}, чтобы увидеть предпросмотр`} isLocal={avatarIsLocal} />
                                </div>
                            </div>
                            <Button type="submit" style={{ marginTop: "16px" }}>Сохранить</Button>
                        </form>
                        <CustomToastsContainer toasts={toasts} setToasts={setToasts} />
                    </>}
            </main >
        </>
    )
}

export default ChatsCreate;