import Table from "react-bootstrap/Table"
import Button from "react-bootstrap/Button"
import { Form } from "react-bootstrap"
import { Plus } from "react-bootstrap-icons"
import { useEffect, useState } from "react"
import Header from "../Header"
import { type Toast as ToastType, type HasUsernameAndId } from "../types"
import CustomToastsContainer from "../CustomToastsContainer"

type ChatResponse = {
    id: number,
    name: string,
    participants: HasUsernameAndId[],
    is_name_auto_generated: boolean
};

type Chat = {
    id: number,
    name: string,
    participants: HasUsernameAndId[],
    isNameAutoGenerated: boolean
};



function ChatsViewPage() {
    document.title = `Просмотр чатов`
    const [chats, setChats] = useState<Chat[]>([]);
    const [searchValue, setSearchValue] = useState("");
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState("");
    const [toasts, setToasts] = useState<ToastType[]>([]);

    async function requestDelete(chatId: number) {
        const response = await fetch(`/api/chats/${chatId}`, {
            method: "DELETE"
        });

        if (response.ok) {
            setToasts(toasts.concat({ headerContent: "Уведомление", bodyContent: "Чат успешно удалён" }))
        } else {
            setToasts(toasts.concat({ headerContent: "Ошибка", bodyContent: "В процессе удаления чата произошла ошибка" }))
        }
    }

    async function getChats() {
        const response = await fetch("/api/chats");
        if (response.ok) {
            const json = await response.json();
            setChats(json.map((chat: ChatResponse) => {
                return {
                    name: chat.name,
                    id: chat.id,
                    participants: chat.participants,
                    isNameAutoGenerated: chat.is_name_auto_generated
                }
            }));
        } else {
            setError("При загрузке чатов произошла ошибка. Возможно, в консоли (Fn + F12) Вы найдёте дополнительную информацию.");
        }

        setLoading(false);
    }

    useEffect(() => {
        getChats();
    }, []);

    function handleChange(event: React.ChangeEvent<HTMLInputElement>) {
        const text = event.target.value;
        setSearchValue(text);

        const url = text ? `/api/search-chats/${text}` : "/api/chats";
        const response = fetch(url);
        response.then(res => {
            if (res.ok) return res.json();
            setToasts(toasts.concat({ headerContent: "Ошибка", bodyContent: "Не удалось загрузить результаты поиска" }));
        }).then(data => {
            if (data) setChats(data.map((item: ChatResponse) => {
                return {
                    ...item,
                    isNameAutoGenerated: item.is_name_auto_generated
                }
            }));
        })
    }

    return (
        <>
            <Header />
            <main className="main">
                <h2 className="heading heading-level-2">Все чаты</h2>
                <div className="tools">
                    <Form.Label htmlFor="search-chats">Поиск чатов</Form.Label>
                    <Form.Control value={searchValue} id="search-chats" placeholder="Введите название или ID чата" onChange={handleChange} />
                    <Button as="a" href="/chats-create" className="create-button"><Plus /> Создать новый чат</Button>
                </div>
                <div className="scrollable">
                    {chats.length ?
                        <Table striped bordered hover>
                            <thead>
                                <tr>
                                    <th className="table-heading">ID</th>
                                    <th className="table-heading">Название</th>
                                    <th className="table-heading">Участники</th>
                                    <th className="table-heading">Название генерируется автоматически?</th>
                                    <th className="table-heading"></th>
                                </tr>
                            </thead>
                            <tbody>
                                {chats.map(chat => (
                                    <tr key={chat.id}>
                                        <td>{chat.id}</td>
                                        <td>{chat.isNameAutoGenerated ? "<Название генерируется автоматически>" : chat.name}</td>
                                        <td>{chat.participants.map(item => item.username).slice(0, 5).join(", ") + (chat.participants.length > 5 ? ` и ещё ${chat.participants.length - 5}` : "")}</td>
                                        <td>{chat.isNameAutoGenerated ? "Да" : "Нет"}</td>
                                        <td><a href={`/chats-edit/${chat.id}`}>Редактировать</a> /
                                            <Button variant="link"
                                                style={{ padding: 0, border: "none", verticalAlign: "baseline" }}
                                                onClick={() => {
                                                    requestDelete(chat.id);
                                                    setChats(chats.filter(item => item !== chat));
                                                }}>Удалить</Button></td>
                                    </tr>
                                ))}
                            </tbody>
                        </Table>
                        : loading ? <p>Загрузка...</p> :
                            (error ? <p>{error}</p> : <p>Чаты не найдены. <a href="/chats-create">Создать новый?</a></p>)}
                </div>
                <CustomToastsContainer toasts={toasts} setToasts={setToasts} />
            </main>
        </>
    )
}

export default ChatsViewPage;